In [60]:
import pandas as pd 
import plotly.express as px

In [61]:
df = pd.read_csv('D:/Users/nickt/Credit_Card_Project/Data/CreditCardData.csv')

In [62]:
df.head()

,Transaction ID,Date,Day of Week,Time,Type of Card,Entry Mode,Amount,Type of Transaction,Merchant Group,Country of Transaction,Shipping Address,Country of Residence,Gender,Age,Bank,Fraud
0,#3577 209,14-Oct-20,Wednesday,19,Visa,Tap,£5,POS,Entertainment,United Kingdom,United Kingdom,United Kingdom,M,25.2,RBS,0
1,#3039 221,14-Oct-20,Wednesday,17,MasterCard,PIN,£288,POS,Services,USA,USA,USA,F,49.6,Lloyds,0
2,#2694 780,14-Oct-20,Wednesday,14,Visa,Tap,£5,POS,Restaurant,India,India,India,F,42.2,Barclays,0
3,#2640 960,13-Oct-20,Tuesday,14,Visa,Tap,£28,POS,Entertainment,United Kingdom,India,United Kingdom,F,51.0,Barclays,0
4,#2771 031,13-Oct-20,Tuesday,23,Visa,CVC,£91,Online,Electronics,USA,USA,United Kingdom,M,38.0,Halifax,1

In [63]:
df.dtypes

Transaction ID                str
Date                          str
Day of Week                   str
Time                        int64
Type of Card                  str
Entry Mode                    str
Amount                        str
Type of Transaction           str
Merchant Group                str
Country of Transaction        str
Shipping Address              str
Country of Residence          str
Gender                        str
Age                       float64
Bank                          str
Fraud                       int64
dtype: object

We will need to convert most of these data types to more sensible ones. Many of these variables are string variables or information related, which may need to be transformed to integer somehow for use in machine learning models.

In [64]:
for col in df.columns: 
    print(df[col].value_counts())

Transaction ID
#2547 017    5
#2617 708    4
#3322 751    3
#3110 310    3
#3321 338    3
            ..
#2960 683    1
#3203 892    1
#3304 849    1
#3532 129    1
#3107 092    1
Name: count, Length: 95680, dtype: int64
Date
14-Oct-20    50184
13-Oct-20    49814
16-Oct-20        1
15-Oct-20        1
Name: count, dtype: int64
Day of Week
Wednesday    50177
Tuesday      49797
Friday          14
Thursday        12
Name: count, dtype: int64
Time
13    5810
16    5785
12    5754
23    5750
11    5748
7     5717
14    5686
15    5685
21    5684
8     5683
17    5665
19    5622
22    5622
10    5610
9     5570
18    5548
20    5522
2      536
3      531
6      515
0      509
5      489
1      484
4      474
24       1
Name: count, dtype: int64
Type of Card
Visa          53812
MasterCard    46188
Name: count, dtype: int64
Entry Mode
PIN    49976
CVC    33481
Tap    16543
Name: count, dtype: int64
Amount
£17     2153
£23     2106
£16     2084
£28     2077
£15     2073
        ...
£124     106
£145     105
£380     102
£375     100
£393      99
Name: count, Length: 396, dtype: int64
Type of Transaction
Online    33481
ATM       33274
POS       33245
Name: count, dtype: int64
Merchant Group
Children         10679
Restaurant       10078
Services         10017
Gaming           10011
Fashion           9987
Subscription      9977
Food              9847
Entertainment     9839
Products          9839
Electronics       9716
Name: count, dtype: int64
Country of Transaction
United Kingdom    71199
USA                7298
Russia             7257
China              7152
India              7094
Name: count, dtype: int64
Shipping Address
United Kingdom    60905
USA               10042
Russia             9799
China              9698
India              9551
Name: count, dtype: int64
Country of Residence
United Kingdom    81859
Russia             4618
USA                4590
China              4529
India              4404
Name: count, dtype: int64
Gender
M    50875
F    49121
Name: count, dtype: int64
Age
43.0    437
43.8    428
45.0    427
46.7    423
45.8    419
       ...
85.7      1
86.1      1
77.2      1
81.8      1
78.8      1
Name: count, Length: 645, dtype: int64
Bank
Barclays    29936
Monzo       10103
RBS         10046
Metro       10012
Barlcays     9993
Halifax      9988
Lloyds       9965
HSBC         9957
Name: count, dtype: int64
Fraud
0    92805
1     7195
Name: count, dtype: int64

We see that the dataset is highly imbalanced, with 93% of transactions being legitimate and ~7% being fraud

We see a discrepancies in our date variable and need to determine the best course of action (wether or not to keep and drop 'Date', 'Day of Week' and 'Time'). We can drop day of the week as it is essentially a copy of the Date.

In [65]:
df['Date'].value_counts()

Date
14-Oct-20    50184
13-Oct-20    49814
16-Oct-20        1
15-Oct-20        1
Name: count, dtype: int64

In [ ]:
fig = px.histogram(df, x="Time")
fig.show()

Now we can check for duplicate values

In [67]:
df.duplicated().sum()

np.int64(0)

We now take a look at the cleaned dataset

In [68]:
df_clean = pd.read_csv('D:/Users/nickt/Credit_Card_Project/Data/CreditCardData_cleaned.csv')

In [69]:
df_clean.head()

,Date,Time,Amount,Age,Fraud,trans_country_mismatch,shipping_residence_mismatch,trans_shipping_mismatch,Type of Card_Visa,Entry Mode_PIN,...,Country of Residence_Russia,Country of Residence_USA,Country of Residence_United Kingdom,Gender_M,Bank_HSBC,Bank_Halifax,Bank_Lloyds,Bank_Metro,Bank_Monzo,Bank_RBS
0,2020-10-14,19,5.0,25.2,0,0,0,0,1,0,...,0,0,1,1,0,0,0,0,0,1
1,2020-10-14,17,288.0,49.6,0,0,0,0,0,1,...,0,1,0,0,0,0,1,0,0,0
2,2020-10-14,14,5.0,42.2,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,2020-10-13,14,28.0,51.0,0,0,1,1,1,0,...,0,0,1,0,0,0,0,0,0,0
4,2020-10-13,23,91.0,38.0,1,1,1,0,1,0,...,0,0,1,1,0,1,0,0,0,0

In [70]:
dupe_ids = df[df.duplicated(subset=['Transaction ID'], keep=False)]
print(dupe_ids.shape)

# Check if ENTIRE rows are duplicated (not just the ID)
full_dupes = df[df.duplicated(keep=False)]
print(full_dupes.shape)

(8519, 16)
(0, 16)